### ISSUE TITLE
Simple... but a little more comment

### ISSUE THREAD

**Issue by tvld** [donniewang/koa-vue-example#1]
We are trying to finalize our choices for the libraries for our new app. Koa + Vue seems the way to go :)

Could you provide a little more comment for the hot code reload / normal build. I find it hard to understand.,..

**Comment by donniewang** [comment]
It uses the webpack-dev-server to provide the hot code reload, you can config it in file build/webpack.dev.config.js.
That normal build actually is running script, you can find it in the file package.json.
